apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-backend
  template:
    metadata:
      labels:
        app: customer-backend
    spec:
      containers:
      - name: customer-backend
        image: docker.io/joeynaor/little-shop-customer-backend
        ports:
        - containerPort: 3000
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: KAFKA_TOPIC
          value: "bought-items"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-backend
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: customer-backend
