apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-frontend
  template:
    metadata:
      labels:
        app: customer-frontend
    spec:
      containers:
      - name: customer-frontend
        image: docker.io/joeynaor/little-shop-customer-frontend
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: customer-frontend
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: customer-frontend
